### ISSUE TITLE
Localhost failed error

### ISSUE THREAD

**Issue by ChristianVeth** [lexcilius/splunk-bots-docker#1]
Having an issue with running the bots1. Tried from Ubuntu 22.04.4, Kali, and Windows 11. Errors are slightly different but seem to be related. 

Screenshots below; 

![error](https://github.com/lexcilius/splunk-bots-docker/assets/129526913/30c2c2a5-c8bb-44ae-9fc6-a28faca6de9f)
![Screenshot from 2024-05-08 21-26-24](https://github.com/lexcilius/splunk-bots-docker/assets/129526913/e65213b6-5067-4a1e-9735-8001fe65ac36)
![Screenshot_2024-05-08_21_10_45](https://github.com/lexcilius/splunk-bots-docker/assets/129526913/d99a08a0-dc91-45cd-b7b0-23925cc13b66)

**Comment by lexcilius** [comment]
I've never personally ran Docker from Kali, but it should work from Ubuntu 22.04 (I've got it running on an instance myself). What versions of Docker and Docker Compose are you running on Ubuntu and Windows?

**Comment by ChristianVeth** [comment]
Do you think the versions are possibly not compatible?

Ubuntu: 

Docker - 26.1.1

Docker Compose - 2.27.0

Windows: 

Docker - version 26.0.0

Docker Compose - 2.26.1

**Comment by lexcilius** [comment]
Likely not a compatibility issue...if anything it would be a nuance in the docker-compose.yml file if that were the case, which would be an easy fix. I'm going to spin up an Ubuntu VM this weekend and test and wanted to compare versions if my test works.

**Comment by ChristianVeth** [comment]
Awesome. Thank you for looking into it. I'll keep on the lookout for an update!

**Comment by lexcilius** [comment]
Ok, just did a fresh install of Ubuntu 22.04, and installed Docker and Docker-Compose-v2 from the default repos and successfully spun up Bots1 with `docker compose up bots1`

`Docker version 24.0.5, build 24.0.5-0ubuntu1~22.04.1`
`Docker Compose version 2.20.2+ds1-0ubuntu1~22.04.1`

It looks like your docker version is much newer than the default one in the repos. Maybe try downgrading it and see if that works. I also have a 24.04 VM I am going to try here in a bit. 

Also, if you want notifications about when updates happen, you can "Watch" the project and get notified when changes happen.

**Comment by ChristianVeth** [comment]
Awesome, I did go ahead and watch the project. 
 
I tried to completely uninstall Docker, and Docker Compose. Then did a fresh install of the same versions that you're using, but received the same error. I may try doing a fresh install of Ubuntu later this week or weekend, then only installing specifically those versions to see what happens. 

Thank you for helping!

**Comment by lexcilius** [comment]
It's also possible depending on the size of your VM, that it might be having a storage issue if you have had multiple failed deploy attempts. You can try a `docker volume prune` and see if that frees up some storage and then give it another go before going through a total rebuild.

**Comment by ChristianVeth** [comment]
Finally had some time to sit down and play with this. I did go ahead and try the `docker volume prune` and it ended up working, as well as doing a fresh install of Ubuntu on my actual laptop as and it worked. Did this with both the versions you used as well as the original versions I used. Works like butter!

**Comment by lexcilius** [comment]
Fantastic! Happy to hear everything worked out. BOTSv2 should be good to go now as well. Happy hunting!
